version: '3.8'
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - seedbox
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - seedbox
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/sonarr/config:/config
      - /home/seedbox/data/media/tv:/media
      - /home/seedbox/data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped


  rtorrent-logs:
    image: bash
    container_name: rtorrent-rutorrent-logs
    command: bash -c 'tail -f /log/*.log'
    network_mode: none
    depends_on:
      - rtorrent-rutorrent
    volumes:
      - "/home/seedbox/apps/rtorrent-rutorrent/data/log:/log"
    restart: always

networks:
  seedbox:
    name: seedbox
    
