version: '3.8'
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/prowlarr/config:/config
    ports:
      - 9696:9696
    labels:
      - "traefik.http.routers.rutorrent.rule=Host(`deslotflix.fr`) && PathPrefix(`/prowlarr`)"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=8080"
    restart: unless-stopped
  rtorrent-rutorrent:
    image: k44sh/rutorrent:latest
    container_name: rtorrent-rutorrent
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${XMLRPC_PORT}"
      - "${RUTORRENT_PORT}"
      - "${WEBDAV_PORT}"
      - "${RT_INC_PORT}"
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    env_file:
      - "rtorrent-rutorrent.env"
      - ".env"
    volumes:
      - "/home/seedbox/apps/rtorrent-rutorrent/config:/config"
      - "/home/seedbox/data/torrents:/data/torrents"
      - "/home/seedbox/apps/rtorrent-rutorrent/passwd:/passwd"
    labels:
      - "traefik.http.routers.rutorrent.rule=Host(`deslotflix.fr`) && PathPrefix(`/rutorrent`)"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=8080"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/sonarr/config:/config
      - /home/seedbox/data:/data
    ports:
      - 8989:8989
    labels:
      - "traefik.http.routers.rutorrent.rule=Host(`deslotflix.fr`) && PathPrefix(`/sonarr`)"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=8080"
    restart: unless-stopped
  radarr: 
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/radarr/config:/config
      - /home/seedbox/data:/data
    ports:
      - 7878:7878
    labels:
      - "traefik.http.routers.rutorrent.rule=Host(`deslotflix.fr`) && PathPrefix(`/radarr`)"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=8080"
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - TZ=Etc/UTC
      - PLEX_CLAIM=claim--_PynKxDKtzWGZPtefEq
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/plex/config:/config
      - /home/seedbox/data/media:/data/media
    ports:
      - 32400:32400
      - 32400:32400/udp
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/overseerr/config:/config
    ports:
      - 5055:5055
    labels:
      - "traefik.http.routers.rutorrent.rule=Host(`deslotflix.fr`) && PathPrefix(`/overseerr`)"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=8080"
    restart: unless-stopped
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock


  rtorrent-logs:
    image: bash
    container_name: rtorrent-rutorrent-logs
    command: bash -c 'tail -f /log/*.log'
    network_mode: none
    depends_on:
      - rtorrent-rutorrent
    volumes:
      - "/home/seedbox/apps/rtorrent-rutorrent/data/log:/log"
    restart: always

networks:
  seedbox:
    name: seedbox
    
