version: '3.8'
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/prowlarr/config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.deslotflix.fr`)"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.docker.network=seedbox"
  rtorrent-rutorrent:
    image: k44sh/rutorrent:latest
    container_name: rtorrent-rutorrent
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${XMLRPC_PORT}"
      - "${WEBDAV_PORT}"
      - "${RT_INC_PORT}"
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    env_file:
      - "rtorrent-rutorrent.env"
      - ".env"
    volumes:
      - "/home/seedbox/apps/rtorrent-rutorrent/config:/config"
      - "/home/seedbox/data/torrents:/data/torrents"
      - "/home/seedbox/apps/rtorrent-rutorrent/passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rutorrent.rule=Host(`rutorrent.deslotflix.fr`)"
      - "traefik.http.routers.rutorrent.tls=true"
      - "traefik.docker.network=seedbox"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=8080"
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/sonarr/config:/config
      - /home/seedbox/data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.deslotflix.fr`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.docker.network=seedbox"
  radarr: 
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/radarr/config:/config
      - /home/seedbox/data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.deslotflix.fr`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.docker.network=seedbox"
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - TZ=Etc/UTC
      - PLEX_CLAIM=claim--_PynKxDKtzWGZPtefEq
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/plex/config:/config
      - /home/seedbox/data/media:/data/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.deslotflix.fr`)"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.docker.network=seedbox"
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      - seedbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    env_file:
      - ".env"
    volumes:
      - /home/seedbox/apps/overseerr/config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.deslotflix.fr`)"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.docker.network=seedbox"

  rtorrent-logs:
    image: bash
    container_name: rtorrent-rutorrent-logs
    command: bash -c 'tail -f /log/*.log'
    network_mode: none
    depends_on:
      - rtorrent-rutorrent
    volumes:
      - "/home/seedbox/apps/rtorrent-rutorrent/data/log:/log"
    restart: always

networks:
  seedbox:
    name: seedbox
    
