version: '3.8'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - seedbox
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ=Etc/UTC
    volumes:
      - /home/seedbox/apps/radarr/config:/config
      - /home/seedbox/medias/movies:/movies #optional
      - /home/seedbox/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    networks:
      - seedbox
    ports:
      - target: "${JACKETT_PORT}"
        published: "${JACKETT_PORT}"
        protocol: tcp
    env_file:
      - ".env"
    environment:
    - PUID="${PUID}"
    - PGID="${PGID}"
    - TZ=Etc/UTC
    - AUTO_UPDATE=true #optional
    - RUN_OPTS= #optional
    volumes:
      - /home/seedbox/apps/jackett/:/config
    restart: unless-stopped
  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent-rutorrent
    networks:
      - seedbox
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${XMLRPC_PORT}"
      - "${RUTORRENT_PORT}"
      - "${WEBDAV_PORT}"
      - "${RT_INC_PORT}"
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    env_file:
      - "rtorrent-rutorrent.env"
      - ".env"
    volumes:
      - "/home/seedbox/apps/rtorrent-rutorrent/data:/data"
      - "/home/seedbox/downloads:/downloads"
      - "/home/seedbox/apps/rtorrent-rutorrent/passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always

  rtorrent-logs:
    image: bash
    container_name: rtorrent-rutorrent-logs
    command: bash -c 'tail -f /log/*.log'
    network_mode: none
    depends_on:
      - rtorrent-rutorrent
    volumes:
      - "/home/seedbox/apps/rtorrent-rutorrent/data/log:/log"
    restart: always

networks:
  seedbox:
    name: seedbox
    
